name: platform_detect2
author: Workiva Client Platform Team <team-clientplatform@workiva.com>
version: 1.5.0+2
homepage: https://github.com/Workiva/platform_detect
documentation: https://www.dartdocs.org/documentation/platform_detect/latest
description: A lightweight library for detecting the running browser and OS
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.9.0
  pub_semver: ^2.1.3
dev_dependencies: 
  build_test: ^1.3.7
  build_web_compilers: ^2.16.4
  test: ^1.16.7
