name: platform_detect2
version: 1.5.0
description: A lightweight library for detecting the running browser and OS
author: Workiva Client Platform Team <team-clientplatform@workiva.com>
homepage: https://github.com/Workiva/platform_detect
documentation: https://www.dartdocs.org/documentation/platform_detect/latest

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  pub_semver: ^2.0.0

dev_dependencies:
#  build_runner: ^1.11.5
  build_test: ^1.3.7
  build_web_compilers: ^2.16.4
  test: ^1.16.7
